<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Обработка-и-анализ-данных-в-Numpy-массивах" data-toc-modified-id="Обработка-и-анализ-данных-в-Numpy-массивах-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Обработка и анализ данных в Numpy-массивах</a></span></li></ul></div>




# Обработка и анализ данных в Numpy-массивах

<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 1</p>

Дано: списки `a,b=[1,1,1],[3,3,3]`

Создать одномерные массивы A и B из списков а и b.

Вычислить выражение $-((B-А)*(B/2))$

In [6]:
import numpy as np

a = [1, 1, 1]
b = [3, 3, 3]
A = np.array(a)
B = np.array(b)

print(A,B) 
step1 = np.subtract(B,A)
print("(𝐵−А) =", step1)

step2 = np.divide(B,2)
print("(𝐵/2) =", step2)

step3 = np.multiply(x1,x3)
print("((𝐵−А)∗(𝐵/2)) =", step3)

result = step3[0] + step3[1] + step3[2]

print("Ответ: ", -result)

[1 1 1] [3 3 3]
(𝐵−А) = [2 2 2]
(𝐵/2) = [1.5 1.5 1.5]
((𝐵−А)∗(𝐵/2)) = [3. 3. 3.]
Ответ:  -9.0


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 2</p>

Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)), добиться расстановки кодов "шахматных фигур".

Ожидаемый результат:
```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
 ```

In [9]:
#2. Ваш код здесь

A = np.zeros((8,8))

A[7] = [4, 3, 2, 6, 5, 2, 3, 4] #заполняем значения доски с нижней стороны
A[0] = -A[7] #используем значение A[7] со знаком - с обратной стороны доски
A[6] = [1, 1, 1, 1, 1, 1, 1, 1] #тоже самое
A[1] = -A[6]

print(A)

[[-4. -3. -2. -6. -5. -2. -3. -4.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  3.  2.  6.  5.  2.  3.  4.]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 3</p>

Средствами NumPy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа

In [11]:
# 3. Ваш код здесь

import numpy as np

# Создание массива четных чисел от 2 до 20
chetnye = np.arange(2, 21, 2) #Функция numpy.arange(start, stop, step) создает массив значений

# Нахождение ближайших к каждому четному числу бОльших нечетных чисел
closest_nechentnye = (chetnye //2) * 2 + 1

# Рассчет произведений четных чисел на ближайшие к ним бОльшие нечетные числа
result = chetnye * closest_nechentnye

print("Четные числа:", chetnye)
print("Ближайшие к ним бОльшие нечетные числа:", closest_nechentnye)
print("Произведения:", result)


Четные числа: [ 2  4  6  8 10 12 14 16 18 20]
Ближайшие к ним бОльшие нечетные числа: [ 3  5  7  9 11 13 15 17 19 21]
Произведения: [  6  20  42  72 110 156 210 272 342 420]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 4</p>

Сгенерировать двумерный массив *arr* размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0. Значения округлить (с помощью `np.round()`) до четырех десятичных знаков.

In [18]:
# 4. Ваш код здесь
arr = np.random.uniform(low = 0.0, high = 20.0, size = (4, 7))

print("До нормализации:\n\n", arr)

print("\n\nФормула нормализации: (X - Xmin)/(Xmax - Xmin). Мы вычитаем минимальное значение из каждой записи, а затем делим результат на диапазон. Где диапазон – это разница между максимальным значением и минимальным значением.\n")

arr_normalized = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))

arr_normalized_rounded = np.round(arr_normalized, decimals = 4)

print("\nПосле нормализации:\n\n",arr_normalized_rounded)


До нормализации:

 [[15.7722794  19.66678347  4.77168615 14.23558793  7.14663153 18.51986518
   9.84404436]
 [17.31967384 11.94693888 17.31257392  9.50548295 14.52862071  7.69896365
   6.65396598]
 [ 1.77244624  1.15090573  9.34973677 14.22913991 15.10426277  9.21596334
  13.68141174]
 [16.91571994 14.24827297  2.02700116  1.37974559  9.69844133 16.43092132
  13.19763564]]


Формула нормализации: (X - Xmin)/(Xmax - Xmin). Мы вычитаем минимальное значение из каждой записи, а затем делим результат на диапазон. Где диапазон – это разница между максимальным значением и минимальным значением.


После нормализации:

 [[0.7897 1.     0.1956 0.7067 0.3238 0.9381 0.4695]
 [0.8732 0.5831 0.8729 0.4512 0.7225 0.3536 0.2972]
 [0.0336 0.     0.4428 0.7063 0.7536 0.4356 0.6767]
 [0.8514 0.7074 0.0473 0.0124 0.4616 0.8252 0.6506]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 5</p>

5. Имеется массив my_array
```
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
```
Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

In [22]:
# 5. Ваш код здесь

my_array = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])

final = np.zeros((3,3)) #создаем двумерный массив final нужного нам размера 3x3, заполненного нулями

i = 1 #пусть i - нужный нам 1 элемент из верхней строчки массива 3х3, с которого начнём считывать массив. 
i_arr = 0 #Т.е. когда мы досчитаем до третьего элемента мы с него начнём брать i_arr 

while i <= 3:
    j = 1
    j_arr = 0
    while j <=3:
        final[i_arr][j_arr] = my_array[i][j] #применяем созданный массив на My_array
        j += 1
        j_arr += 1
    i += 1
    i_arr += 1
    
print(final)

[[ 7.  8.  9.]
 [12. 13. 14.]
 [17. 18. 19.]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 6</p>

Создайте массив *my_sin*, состоящий из синусов элементов массива *my_array*.
Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до
трёх цифр после запятой.

In [44]:
# 6. Ваш код здесь
import numpy as np

my_array = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])

my_sin = np.sin(my_array)
my_sin_round = np.round(my_sin, decimals = 3)

summa = np.sum(my_sin_round) #используем метод sum

print(f"Массив my_sin:\n\n{my_sin_round}\n")
print(f"\nСумма элементов массива: {np.round(summa, 3)}\n")

Массив my_sin:

[[ 0.841  0.909  0.141 -0.757 -0.959]
 [-0.279  0.657  0.989  0.412 -0.544]
 [-1.    -0.537  0.42   0.991  0.65 ]
 [-0.288 -0.961 -0.751  0.15   0.913]
 [ 0.837 -0.009 -0.846 -0.906 -0.132]]


Сумма элементов массива: -0.059



<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 7</p>

Создать матрицу из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в матрице. Определить индекс этого значения.

In [49]:
# 7. Ваш код здесь
from numpy import random
import numpy as np

arr = random.randint(100, size = (10,2))

print(arr)

value = arr[0:1, 1]

print("Второе сверху значение в матрице:", value)

ind = np.where(arr == value)
ind = list(zip(ind[0], ind[1]))

print("Индекс этого значения:", ind)

[[53 94]
 [25 47]
 [31 51]
 [37 85]
 [14 96]
 [47 82]
 [19 64]
 [15 84]
 [61 99]
 [62 40]]
Второе сверху значение в матрице: [94]
Индекс этого значения: [(0, 1)]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 8</p>

Задать два двухмерных массива *ar1* и *ar2* размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максимум (минимум, среднее) из двух значений, находящихся на аналогичной позиции в массивах *ar1*, *ar2*.

In [18]:
# 8. Ваш код здесь
ar1 = random.randint(10, size = (4,7))
ar2 = random.randint(10, size = (4,7))

print ("ar1:\n", ar1)
print ("\nar2:\n", ar2)

ar3 = np.zeros((4,7))

print ('')
    
i = 0
while i < 4:
    j = 0
    while j < 7:
        ar3[i][j] = max(ar1[i][j], ar2[i][j])
        #ar3[i][j] = min(ar1[i][j],ar2[i][j])
        #ar3[i][j] = np.add(ar1[i][j],ar2[i][j])/2
        j += 1
    i +=1
print ("ar3:\n", ar3)

ar1:
 [[1 0 6 9 9 5 4]
 [3 1 9 7 4 4 8]
 [0 2 6 1 9 6 5]
 [5 4 6 7 1 1 1]]

ar2:
 [[7 4 6 2 9 3 8]
 [3 3 8 5 4 8 8]
 [7 8 5 6 1 2 7]
 [1 6 2 3 0 3 2]]

ar3:
 [[7. 4. 6. 9. 9. 5. 8.]
 [3. 3. 9. 7. 4. 8. 8.]
 [7. 8. 6. 6. 9. 6. 7.]
 [5. 6. 6. 7. 1. 3. 2.]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 9</p>

Имеется массив *great_array*
```
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
```
Чему равна сумма элементов массива great_array, значение которых больше 50?

In [21]:
#9 Ваш код здесь

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T

#print(great_array)

summ = np.sum(great_array[great_array > 50])
print(summ)



5470.0


Вычисляется сумма всех элементов в great_array больших чем 50 с помощью np.sum(great_array[great_array > 50]). Функция great_array > 50 создает маску, содержащую значения True для элементов больших чем 50, после чего np.sum используется для вычисления суммы всех таких элементов.

<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 10</p>

Переведите массив *great_array* в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?

In [24]:
# 10. Ваш код здесь

flattened_arr = great_array.flatten() #Эта функция принимает двумерный массив в качестве аргумента и возвращает его в виде одномерного массива.

print("Элемент с индексом 150 равен", flattened_arr[150])

Элемент с индексом 150 равен 7.0710678118654755


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 11</p>

Получить индексы, для которых элементы массивов A и B совпадают.
```
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
```
Ожидается результат:

```
array([1, 3, 5, 7])
```

In [25]:
# 11.

A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

# Ваш код здесь

array = np.where(A == B)[0]
print(array)


[1 3 5 7]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 12</p>

Создайте три массива: массив четных чисел от 2 до 20, массив ближайших к числам первого массива бОльших нечётных чисел, массив векторного произведения первого массива на второй. Соедините все массивы в один двумерный массив, расположив исходные массивы в столбцах.

In [31]:
# 12.  Ваш код здесь

import numpy as np

# Создание массива четных чисел от 2 до 20
chetnye = np.arange(2, 21, 2) #Функция numpy.arange(start, stop, step) создает массив значений

# Создание массива ближайших к каждому четному числу бОльших нечетных чисел
nechentnye = (chetnye//2) * 2 + 1

proizvedenie = np.multiply(chetnye, nechentnye)

result = np.column_stack((chetnye, nechentnye, proizvedenie))

print (result)

[[  2   3   6]
 [  4   5  20]
 [  6   7  42]
 [  8   9  72]
 [ 10  11 110]
 [ 12  13 156]
 [ 14  15 210]
 [ 16  17 272]
 [ 18  19 342]
 [ 20  21 420]]
